name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  type-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [client, server]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        working-directory: ./${{ matrix.project }}
        run: npm install

      - name: TypeScript Check
        working-directory: ./${{ matrix.project }}
        run: npx tsc --noEmit
